CharacterNexus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'CharacterNexus'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeSite.urls')),
    path('charIndex/', include('charIndex.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

charIndex/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'charIndex'
urlpatterns = [
    path('<str:char_origin>/<str:char_name>/', views.CharacterDetailsView.as_view(), name='detail'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

homeSite/urls.py
from django.urls import path

from . import views

app_name = 'homeSite'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
#class User(AbstractUser):
#    pass

charIndex/models.py
from django.db import models


# Create your models here.
class Character(models.Model):
    # Create the path for the character image that is to be uploaded.
    def get_image_path(self, filename):
        return '{0}/{1}'.format(self.char_origin, filename)

    char_name = models.CharField('character name', max_length=200)
    char_img = models.ImageField(upload_to=get_image_path, blank=False, null=True)
    char_origin = models.CharField('character origin', max_length=200)
    pub_date = models.DateTimeField('date created')

    def __str__(self):
        return self.char_name


class Stats(models.Model):
    character = models.OneToOneField(
        Character,
        on_delete=models.CASCADE,
        primary_key=True)
    rarity = models.CharField('Rarity', max_length=200)
    movement_speed = models.IntegerField('Movement speed', null=True)
    health = models.IntegerField('Health', null=True)
    range = models.DecimalField('Range', null=True, max_digits=4, decimal_places=2)
    reload_speed = models.DecimalField('Reload speed', null=True, max_digits=4, decimal_places=2)
    bullets_per_attack = models.IntegerField('Bullets per attack', null=True)
    damage_per_bullet = models.IntegerField('Damage per bullet', null=True)
    super_range = models.DecimalField('Super range', null=True, max_digits=4, decimal_places=2)
    bullets_per_super = models.IntegerField('Bullets per super', null=True)
    super_damage_per_bullet = models.IntegerField('Super damage per bullet', null=True)

    def get_fields(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in Stats._meta.fields]

    def __str__(self):
        return "{}'s character stats.".format(self.character.char_name)

CharacterNexus/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, help_text='Required. Input a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from CharacterNexus.forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

charIndex/views.py
# Views for the app charIndex.
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.db.models import Q
from django.contrib.auth import views as auth_views

from .models import Character, Stats


# Create your views here.
class CharacterDetailsView(generic.DetailView):
    model = Stats
    template_name = 'CharacterNexus/detail.html'
    context_object_name = 'character'

    def get_object(self, **kwargs):
        return get_object_or_404(
            Character,
            char_name=self.kwargs['char_name'],
            char_origin=self.kwargs['char_origin'])


class SearchResultsView(generic.ListView):
    model = Character
    template_name = 'CharacterNexus/search_results.html'
    context_object_name = 'relevant_characters'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if len(query) > 4:
            object_list = Character.objects.filter(
                Q(char_name__icontains=query) | Q(char_origin__icontains=query)
            )
        else:
            object_list = Character.objects.filter(
                Q(char_name__icontains=query)
            )
        return object_list

# class TeamBuilderView(generic.ListView):
#    model = Character
#    template_name = 'CharacterNexus/team_builder.html'

homeSite/views.py
# Views for the app homeSite
from django.views import generic
from django.utils import timezone

from charIndex.models import Character


# Create your views here.
class IndexView(generic.ListView):
    model = Character
    template_name = 'CharacterNexus/index.html'
    context_object_name = 'newest_characters_list'

    def get_queryset(self):
        return Character.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

templates/CharacterNexus/base.html
<!-- templates/CharacterNexus/base.html -->
<!DOCTYPE html>
<html>
    <header>
        {% block header %}
        {% endblock %}

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'charIndex/style.css' %}">

    </header>
    <body>
        <!-- Navbar for the webpage -->
        <ul>
            <li><a href="{% url 'homeSite:index' %}">Home</a></li>
            <li><a href="news.asp">News</a></li>
            <li><a href="contact.asp">Contact</a></li>
            <li><a href="about.asp">About</a></li>
        </ul>

        {% block login %}

        <!-- Login button -->
        {% if user.is_authenticated %}
            <p>Hi {{ user.username }}!</p>
            <p><a href="{% url 'logout' %}">Logout</a></p>
        {% else %}
            <p>
                <a href="{% url 'login' %}">Login</a>
                 /
                <a href="{% url 'accounts:signup' %}">Sign Up</a>
            </p>
        {% endif %}
        {% endblock %}

        {% block search_bar %}
        <!-- Search bar -->
        <form action="{% url 'charIndex:search_results' %}" autocomplete="off" method="get">
            <input name="q" type="text" placeholder="Search...">
            <input type="submit" value="Search">
        </form>
        {% endblock %}

        {% block content %}
        {% endblock %}
    </body>
</html>

templates/CharacterNexus/detail.html
{% extends "CharacterNexus/base.html" %}

{% block header %}
    <title>{{ character.char_origin }} - {{ character.char_name }}</title>
{% endblock %}

{% block content %}
    <h1>{{ Character.char_name }}</h1>
    <img src="{{ character.char_img.url }}" class="char_img">
    <figcaption>{{ character.char_name }}</figcaption>
    <p>
        {% for name, value in character.stats.get_fields|slice:"1:" %}
            {% if value %}
                {{ name }} => {{ value }}
                <br>
            {% endif %}
        {% endfor %}
    </p>
{% endblock %}

templates/CharacterNexus/index.html
<!-- templates/CharacterNexus/index.html -->
{% extends "CharacterNexus/base.html" %}

{% block header %}
    <title>CharacterNexus</title>
{% endblock %}

{% block content %}
    {% if newest_characters_list %}
        {% for character in newest_characters_list %}
            <a href="{% url 'charIndex:detail' character.char_origin  character.char_name %}">
                <img src="{{ character.char_img.url }}" class="char_img">
                <figcaption>
                    {{ character.char_name }}
                </figcaption>
            </a>
        {% endfor %}
    {% else %}
        <p>There are no characters in the nexus yet.</p>
    {% endif %}
{% endblock %}

templates/CharacterNexus/search_results.html
<!-- templates/CharacterNexus/search_results.html -->
{% extends "CharacterNexus/base.html" %}

{% block header %}
    <title>CharacterNexus</title>
{% endblock %}

{% block content %}
    {% if relevant_characters %}
        {% for character in relevant_characters %}
            <a href="{% url 'charIndex:detail' character.char_origin  character.char_name %}">
                <img src="{{ character.char_img.url }}" class="char_img">
                <figcaption>
                    {{ character.char_name }}
                </figcaption>
            </a>
        {% endfor %}
    {% else %}
        <p>Your search returned none of the characters in the nexus.</p>
    {% endif %}
{% endblock %}